---
title: "Replication of Zhang (2009)"
output: html_document
date: '2022-06-10'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

# Round 1
```{r round1}
# Reading, cleaning, and reshaping the data
round1_dat <- read.csv("round1_raw.csv") %>% 
  select(session.code, ipo_task.1.group.id_in_subsession, participant.id_in_session, 
         contains("group.market_price"), ipo_task.20.player.total_missing_responses) %>% # select only required variables
  filter(ipo_task.1.group.id_in_subsession != 1) %>% # use only completed groups
  rename(group_in_session = ipo_task.1.group.id_in_subsession,# rename group variable and the number of rounds missed
         rounds_missed = ipo_task.20.player.total_missing_responses) %>% 
  pivot_longer(cols = starts_with("ipo_task."), # reshape the data from wide to long
               names_to = c("round", "player_level", "character"),
               names_sep = "\\.",
               names_prefix = "ipo_task.",
               values_to = "market_price") %>% 
  group_by(session.code, group_in_session) %>% 
  dplyr::mutate(rounds_missed_max = max(rounds_missed),
         rounds_missed_min = min(rounds_missed)) %>% 
  dplyr::mutate(bankrupt = ifelse(rounds_missed_min == -99, 1, 0),
         dropout = ifelse(rounds_missed_max >= 6, 1, 0))

# Average market price by group 
round1_dat_collapsed <- round1_dat %>% 
  group_by(session.code, group_in_session, bankrupt, dropout) %>% 
  summarise(market_price = mean(market_price)) %>% 
  filter(!is.na(market_price) & bankrupt != 1 & dropout != 1)

# Wilcoxon Signed Rank Test
with(round1_dat_collapsed, wilcox.test(market_price, mu = 1.94))
```


# Round 2
```{r round2}
# Reading, cleaning, and reshaping the data
round2_dat <- read.csv("round2_raw.csv") %>% 
  select(session.code, ipo_task.1.group.id_in_subsession, participant.id_in_session, 
         contains("group.market_price"), ipo_task.20.player.total_missing_responses) %>% # select only required variables
  filter(ipo_task.1.group.id_in_subsession != 1) %>% # use only completed groups
  rename(group_in_session = ipo_task.1.group.id_in_subsession,# rename group variable and the number of rounds missed
         rounds_missed = ipo_task.20.player.total_missing_responses) %>% 
  pivot_longer(cols = starts_with("ipo_task."), # reshape the data from wide to long
               names_to = c("round", "player_level", "character"),
               names_sep = "\\.",
               names_prefix = "ipo_task.",
               values_to = "market_price") %>% 
  group_by(session.code, group_in_session) %>% 
  mutate(rounds_missed_max = max(rounds_missed),
         rounds_missed_min = min(rounds_missed)) %>% 
  mutate(bankrupt = ifelse(rounds_missed_min == -99, 1, 0),
         dropout = ifelse(rounds_missed_max >= 6, 1, 0))

# Average market price by group 
round2_dat_collapsed <- round2_dat %>% 
  group_by(session.code, group_in_session, bankrupt, dropout) %>% 
  summarise(market_price = mean(market_price)) %>% 
  filter(!is.na(market_price) & bankrupt != 1 & dropout != 1)

# Wilcoxon Signed Rank Test
with(round2_dat_collapsed, wilcox.test(market_price, mu = 1.94))
```


# Round 1 and Round 2 Combined
```{r combined}
# Merge Round 1 collapsed dataset and Round 2 collapsed dataset
merged_dat_collapsed <- rbind(round1_dat_collapsed, round2_dat_collapsed)

# Wilcoxon Signed Rank Test
with(merged_dat_collapsed, wilcox.test(market_price, mu = 1.94))
```


