---
title: "LeBoeuf_JournMarketRes_2010_EKBZ_Yoon_Direct Replication_618K_Final"
author: "Sangsuk Yoon"
date: "11/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=F, warning=F, message=F, include=F}
# Load required packages
Packages <- c("readxl","readr","tidyverse","ggplot2","kableExtra","pander","dplyr","emmeans","sjstats","tibble","reshape2","ggpubr")
lapply(Packages, library, character.only = TRUE)
```


```{r, echo=F}
# Read Data
setwd('~/Dropbox/Research/Brand/submitted materials/analysis/') # set the directory
dat <- read_csv("LeBeouf_replication_data.csv") # read the dataset
items <- read_xlsx("ItemsList_Final.xlsx") # read the stimuli dataset
```


```{r, echo=F}
# Excluding outliers
dat <- dat %>% 
  filter(Status == 0) |>  # Exclude "Preview" sessions and non-main sessions
  filter(!is.na(screenQ)) |> # Exclude incomplete respondents (ScreenQ was the last question of the study)
  filter(Attention1 == 7) |> # Attention Check Question 1
  filter(Attention2 == 1) |> # whether the respondents have taken the study seriously
  filter(screenQ == 2) # whether they have participated in the study before (to excluded repeating participants)

```


```{r, echo=F, warning=F, message=F}
# Cleaning data
dat <- dplyr::select(dat, -c(StartDate:Q1)) #delete first several unncessary columns (e.g., start time, etc.)
dat <- tibble::rowid_to_column(dat, "ID") # Impose ID to each participant 
dat$ID <- as.factor(dat$ID) # Make the ID variable as a factor variable 
dat <- dplyr::select(dat, -starts_with("Familiarity")) # Delete familiarity ratings since they are not parts of the main DVs
dat <- dplyr::select(dat, -contains("Bipol")) # Delete the Utilitarian vs. Hedonic bipolar ratings since they are not the main DVs
```


```{r, echo=F, warning=F, message=F}
## Restructuring the data 

## Create separate data frames for the three conditions (control vs. Brand A vs. Brand B)

dat.control <- dat %>% filter(Cond == 1 | Cond == 2) # Control (NoBrand) conditions 
dat.control <- dat.control %>% 
  select(-contains("Util_1") & -contains("Util_2")) %>% 
  select(-contains("Symbol_1") & -contains("Symbol_2")) %>% 
  select(-contains("Bipol_1") & -contains("Bipol_2"))

dat.brandA <- dat %>% filter(Cond == 3) # Brand A condition
dat.brandA <- dat.brandA %>% 
  select(-ends_with("Util") & -contains("Util_2")) %>% 
  select(-ends_with("Symbol") & -contains("Symbol_2")) %>% 
  select(-ends_with("Bipol") & -contains("Bipol_2"))

dat.brandB <- dat %>% filter(Cond == 4) # Brand B condition 
dat.brandB <- dat.brandB %>% 
  select(-ends_with("Util") & -contains("Util_1")) %>% 
  select(-ends_with("Symbol") & -contains("Symbol_1")) %>% 
  select(-ends_with("Bipol") & -contains("Bipol_1"))

##=============================================================================

## Reshape each condition's data frame from wide to long

control_long <- dat.control %>% 
  select_if(~ !any(is.na(.))) %>% 
  reshape(., 
          idvar = c("ID","Cond"), 
          timevar = "ItemCatID",
          varying = list(c(2,4,6,8,10,12,14,16), c(3,5,7,9,11,13,15,17)), 
          v.names = c("Benefits", "Symbols"), 
          direction = "long") |>
  arrange(ID)

brandA_long <- dat.brandA %>% 
  select_if(~ !any(is.na(.))) %>% 
  reshape(., 
          idvar = c("ID","Cond"), 
          timevar = "ItemCatID",
          varying = list(c(2,4,6,8,10,12,14,16), c(3,5,7,9,11,13,15,17)), 
          v.names = c("Benefits", "Symbols"), 
          direction = "long")|>
  arrange(ID)

brandB_long <- dat.brandB %>% 
  select_if(~ !any(is.na(.))) %>% 
  reshape(., 
          idvar = c("ID","Cond"), 
          timevar = "ItemCatID",
          varying = list(c(2,4,6,8,10,12,14,16), c(3,5,7,9,11,13,15,17)), 
          v.names = c("Benefits", "Symbols"), 
          direction = "long")|>
  arrange(ID)

## create a new variable "Condition" that distinguishes between the Category and Brand conditions
control_long$Condition <- "Category"
brandA_long$Condition <- "Brand"
brandB_long$Condition <- "Brand"

##================================================================================

combined <- rbind(control_long, brandA_long, brandB_long) # Combined the three conditions' data frames into one data frame
combined <- combined %>% full_join(items, by = c("ItemCatID", "Cond")) # merge the combined data with the stimuli data frame
combined <- combined %>% mutate(ScoreDiff = Benefits - Symbols) # Create the main DV (difference between benefits ratings - symbolic rationgs)

# Collapse the data by each participant, condition (Category (or NoBrand) vs. Brand), and product types (Hedonic vs. Symbolic)
dat_collapsed <- combined %>% 
  group_by(ID, ProductType, Condition) %>% 
  summarise(ScoreDiff = mean(ScoreDiff))
```

# Descriptive Statistics
## Utilitarian Items 
```{r, echo=F, warning=F, message=F}
## Descriptive Statistics by Items

## Utilitarian Items 
combined %>% 
  filter(ProductType == "Utilitarian") %>% 
  group_by(Condition, Category) %>%
  summarise(Mean=mean(ScoreDiff)) %>% 
  dcast(Category ~ Condition, value.var="Mean") %>% 
  pander()
```

## Symbolic Items
```{r, echo=F, warning=F, message=F}
## Symbolic Items 
combined %>% 
  filter(ProductType == "Symbolic") %>% 
  group_by(Condition, Category) %>%
  summarise(Mean=mean(ScoreDiff)) %>% 
  dcast(Category ~ Condition, value.var="Mean") %>% 
  pander()
```

## By Level (category vs. brand) nd Product Type (utilitarian vs. symbolism)
```{r, echo=F, warning=F, message=F}
## Descriptive Statistics by Conditions

dat_collapsed %>%
  group_by(Condition, ProductType) %>%
  summarise(Mean=mean(ScoreDiff)) %>% 
  spread(Condition, Mean) %>%
  pander()
```


# ANOVA Test Result
```{r, echo=F, warning=F, message=F}
# ANOVA
model1 <- aov(ScoreDiff ~ Condition*ProductType + Error(ID/ProductType), data=dat_collapsed)
summary(model1)

# Graph 
ggbarplot(dat_collapsed, 
          x = "ProductType", y = "ScoreDiff", color="Condition",
          add = c("mean_se"),
          position = position_dodge(0.8), 
          label = TRUE, lab.nb.digits = 2, 
          ylab = "Benefit-Symbolism Difference Score", 
          xlab = "Unbranded Product Type") + 
  labs(colour = "Level")

# Effect Size
eta_sq(model1, partial=TRUE)

# Post-hoc Test
contrast.condition <- emmeans(model1, pairwise ~ Condition|ProductType, adjust="tukey")
contrast.condition$contrasts

contrast.producttype <- emmeans(model1, pairwise ~ ProductType|Condition, adjust="tukey")
contrast.producttype$contrasts
```

